### ISSUE TITLE
[Question]How to set RX?

### ISSUE THREAD

**Issue by xang555** [sllurp/sllurp#179]
How to set Rx to Impinj reader

**Comment by fviard** [comment]
You mean, how to set the Rx antenna?
For Impinj, I don't think that the you can use different antenna for sending and for receiving.
The same antenna will be used for both.

**Comment by xang555** [comment]
> You mean, how to set the Rx antenna? For Impinj, I don't think that the you can use different antenna for sending and for receiving. The same antenna will be used for both.

Thanks to reply 

I mean how to config RX value using this package? can you provide example to do that?

Thanks to advance

**Comment by thijmenketel** [comment]
I don't exactly know how to configure the receiver sensitivity, however I remember that there's a way to extract the ReceiveSensitivityTableEntry from the reader. Unfortunately I can't find it anymore in this repo, it's still there on my (extremely dated) [fork](https://github.com/thijmenketel/sllurp/blob/0fe88eb2ddb262f54292cbdd5a145b0a2fec37d3/sllurp/llrp_proto.py#L1471). 

I do not have a reader to use anymore as I'm no longer at university so you'll have to try to find a solution yourself.
