### ISSUE TITLE
Frequency Range

### ISSUE THREAD

**Issue by nikga123** [sllurp/sllurp#185]
I am new to sllurp, as well as RFID readers. I want to find out if it is possible to limit a specific frequency range with Speedway R220 readers. I have some devices that the readers are interfering with when these are in range (and primarily when the reader antenna is set to full power). The devices in question operate in the 929 MHz range. I understand that RFID readers are just under this (at the high end), but they still interfere, sometimes always, sometime intermittently.

I've attempted setting FixedFrequencyMode, but I am not allowed to use this option as it is invalid in my region (FCC_Part_15_247).

Here is a sample of my attempt:

```
impinj_fixed_frequency_param = {
    'FixedFrequencyMode': 0,  # It errors if I set it to one
    'ChannelListIndex': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 
                         19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
}

self.factory = llrp.LLRPClientFactory(
    report_every_n_tags=1,
    antennas=(1),
    tx_power=91,
    impinj_fixed_frequency_param=impinj_fixed_frequency_param,
    reset_on_connect=True
)
```

**UPDATE:**

Maybe what I am looking for is setting the hop table, if possible. I started digging into this, but no luck so far.

Thank you.

**Comment by fviard** [comment]
In my memory, if you are using an Impinj reader set to the FCC region, you are forced to use the frequency hopping that is using the whole spectrum of frequencies, and you don't have the possibility to reduce the list of frequencies used for that.
